"""Markdown report generation for V0 experiment runs."""

from __future__ import annotations

from pathlib import Path


def generate_report(
    *,
    strategy_name: str,
    metrics: dict[str, float | int],
    trade_count: int,
    output_path: Path,
) -> Path:
    """Write a compact markdown report and return its path."""
    lines = [
        f"# V0 Backtest Report: {strategy_name}",
        "",
        "## Metrics",
        "",
        "| metric | value |",
        "| --- | ---: |",
    ]
    for key in sorted(metrics):
        lines.append(f"| {key} | {metrics[key]} |")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            f"- Filled trades: {trade_count}",
            "- Data source: `data/validation/sample_markets.csv`",
            "- Metrics are deterministic and generated by local code.",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
