"""Deterministic static HTML chart generation for round artifacts."""

from __future__ import annotations

import csv
import html
import json
from pathlib import Path


CHART_SCHEMA_VERSION = "round_chart_v1"
SERIES_COLORS = {
    "train": "#2563eb",
    "validation": "#059669",
    "holdout": "#dc2626",
}


def generate_round_chart(
    *,
    output_path: Path,
    run_id: str,
    round_id: str,
    metrics_paths: dict[str, Path],
    trades_paths: dict[str, Path],
) -> Path:
    """Write a deterministic, dependency-free HTML chart for one round."""
    metrics = {
        split: load_metrics(path)
        for split, path in sorted(metrics_paths.items())
    }
    series = {
        split: cumulative_pnl(load_trade_pnls(path))
        for split, path in sorted(trades_paths.items())
    }
    output_path.write_text(
        render_chart_html(
            run_id=run_id,
            round_id=round_id,
            metrics=metrics,
            series=series,
        ),
        encoding="utf-8",
    )
    return output_path


def load_metrics(path: Path) -> dict[str, float | int]:
    """Load a metrics JSON object from disk."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        return {}
    return {
        str(key): value
        for key, value in payload.items()
        if isinstance(value, int | float)
    }


def load_trade_pnls(path: Path) -> list[float]:
    """Load trade PnL values from a CSV file."""
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return [
            float(row.get("pnl", 0.0) or 0.0)
            for row in reader
        ]


def cumulative_pnl(pnls: list[float]) -> list[float]:
    """Return cumulative PnL points including the zero origin."""
    total = 0.0
    points = [0.0]
    for pnl in pnls:
        total += pnl
        points.append(round(total, 6))
    return points


def render_chart_html(
    *,
    run_id: str,
    round_id: str,
    metrics: dict[str, dict[str, float | int]],
    series: dict[str, list[float]],
) -> str:
    """Return deterministic HTML for the round chart artifact."""
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            f'<meta name="suan-chart-schema" content="{CHART_SCHEMA_VERSION}">',
            f"<title>SuanAgent Chart - {escape(run_id)} {escape(round_id)}</title>",
            "<style>",
            chart_css(),
            "</style>",
            "</head>",
            "<body>",
            "<main>",
            "<header>",
            "<h1>SuanAgent Round Chart</h1>",
            f"<p>Run <strong>{escape(run_id)}</strong> / Round <strong>{escape(round_id)}</strong></p>",
            "</header>",
            '<section class="panel">',
            "<h2>Cumulative PnL</h2>",
            render_svg(series),
            '<p class="note">Static HTML generated by deterministic local code. No external assets, scripts, or network calls.</p>',
            "</section>",
            '<section class="panel">',
            "<h2>Metrics</h2>",
            render_metrics_table(metrics),
            "</section>",
            "</main>",
            "</body>",
            "</html>",
            "",
        ]
    )


def chart_css() -> str:
    """Return compact CSS for the static chart page."""
    return """
:root { color-scheme: light; font-family: Arial, Helvetica, sans-serif; }
body { margin: 0; background: #f8fafc; color: #111827; }
main { max-width: 980px; margin: 0 auto; padding: 24px; }
header { margin-bottom: 18px; }
h1 { margin: 0 0 6px; font-size: 28px; line-height: 1.2; }
h2 { margin: 0 0 12px; font-size: 18px; line-height: 1.3; }
p { margin: 0; }
.panel { background: #ffffff; border: 1px solid #d1d5db; border-radius: 8px; padding: 18px; margin: 16px 0; }
.chart { width: 100%; height: auto; display: block; border: 1px solid #e5e7eb; background: #ffffff; }
.axis { stroke: #9ca3af; stroke-width: 1; }
.grid { stroke: #e5e7eb; stroke-width: 1; }
.series { fill: none; stroke-width: 3; }
.legend text { font-size: 13px; fill: #374151; }
.note { color: #4b5563; font-size: 13px; margin-top: 10px; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
th, td { border-bottom: 1px solid #e5e7eb; padding: 8px; text-align: right; }
th:first-child, td:first-child { text-align: left; }
th { color: #374151; background: #f9fafb; }
""".strip()


def render_svg(series: dict[str, list[float]]) -> str:
    """Return an inline SVG line chart for cumulative PnL series."""
    width = 900
    height = 360
    left = 54
    right = 24
    top = 24
    bottom = 46
    plot_width = width - left - right
    plot_height = height - top - bottom
    values = [
        value
        for points in series.values()
        for value in points
    ] or [0.0]
    min_y = min(0.0, min(values))
    max_y = max(0.0, max(values))
    if min_y == max_y:
        max_y += 1.0
        min_y -= 1.0
    max_x = max((len(points) - 1 for points in series.values()), default=1)
    max_x = max(max_x, 1)
    zero_y = scale_y(0.0, min_y, max_y, top, plot_height)
    lines = [
        f'<svg class="chart" viewBox="0 0 {width} {height}" role="img" aria-label="Cumulative PnL by split">',
        f'<line class="axis" x1="{left}" y1="{top}" x2="{left}" y2="{top + plot_height}" />',
        f'<line class="axis" x1="{left}" y1="{zero_y:.2f}" x2="{left + plot_width}" y2="{zero_y:.2f}" />',
    ]
    for index in range(5):
        y = top + index * plot_height / 4
        value = max_y - index * (max_y - min_y) / 4
        lines.append(
            f'<line class="grid" x1="{left}" y1="{y:.2f}" x2="{left + plot_width}" y2="{y:.2f}" />'
        )
        lines.append(
            f'<text x="10" y="{y + 4:.2f}" font-size="12" fill="#4b5563">{value:.2f}</text>'
        )
    legend_y = height - 20
    for legend_index, (split, points) in enumerate(sorted(series.items())):
        color = SERIES_COLORS.get(split, "#111827")
        path = svg_path(points, min_y, max_y, max_x, left, top, plot_width, plot_height)
        lines.append(
            f'<path class="series" d="{path}" stroke="{color}" />'
        )
        legend_x = left + legend_index * 150
        lines.append('<g class="legend">')
        lines.append(
            f'<line x1="{legend_x}" y1="{legend_y}" x2="{legend_x + 22}" y2="{legend_y}" stroke="{color}" stroke-width="3" />'
        )
        lines.append(
            f'<text x="{legend_x + 30}" y="{legend_y + 4}">{escape(split)}</text>'
        )
        lines.append("</g>")
    lines.append("</svg>")
    return "\n".join(lines)


def svg_path(
    points: list[float],
    min_y: float,
    max_y: float,
    max_x: int,
    left: int,
    top: int,
    plot_width: int,
    plot_height: int,
) -> str:
    """Return an SVG path string for one cumulative PnL series."""
    if not points:
        points = [0.0]
    commands = []
    for index, value in enumerate(points):
        x = left + (index / max_x) * plot_width
        y = scale_y(value, min_y, max_y, top, plot_height)
        command = "M" if index == 0 else "L"
        commands.append(f"{command}{x:.2f},{y:.2f}")
    return " ".join(commands)


def scale_y(
    value: float,
    min_y: float,
    max_y: float,
    top: int,
    plot_height: int,
) -> float:
    """Scale a data value to SVG y coordinates."""
    return top + (max_y - value) / (max_y - min_y) * plot_height


def render_metrics_table(metrics: dict[str, dict[str, float | int]]) -> str:
    """Return an HTML table of selected metrics by split."""
    metric_keys = (
        "ev",
        "total_pnl",
        "max_drawdown",
        "trade_count",
        "fill_rate",
        "avg_slippage",
    )
    lines = [
        "<table>",
        "<thead>",
        "<tr><th>Split</th>"
        + "".join(f"<th>{escape(key)}</th>" for key in metric_keys)
        + "</tr>",
        "</thead>",
        "<tbody>",
    ]
    for split, values in sorted(metrics.items()):
        cells = [f"<td>{escape(split)}</td>"]
        for key in metric_keys:
            value = values.get(key, "")
            cells.append(f"<td>{format_metric(value)}</td>")
        lines.append("<tr>" + "".join(cells) + "</tr>")
    lines.extend(["</tbody>", "</table>"])
    return "\n".join(lines)


def format_metric(value: object) -> str:
    """Return stable metric text for HTML tables."""
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:.6f}"
    return ""


def escape(value: object) -> str:
    """HTML-escape a value."""
    return html.escape(str(value), quote=True)
