"""Deterministic static HTML trade-timeline generation."""

from __future__ import annotations

import csv
import html
from pathlib import Path
from typing import Any


TIMELINE_SCHEMA_VERSION = "trade_timeline_v1"
TIMELINE_COLUMNS = (
    "split",
    "timestamp",
    "market_id",
    "side",
    "requested_price",
    "fill_price",
    "stake",
    "quantity",
    "outcome",
    "pnl",
    "slippage",
    "reason",
)


def generate_trade_timeline(
    *,
    output_path: Path,
    run_id: str,
    round_id: str,
    trades_paths: dict[str, Path],
) -> Path:
    """Write a deterministic, dependency-free trade timeline for one round."""
    rows = timeline_rows(trades_paths)
    output_path.write_text(
        render_timeline_html(
            run_id=run_id,
            round_id=round_id,
            rows=rows,
        ),
        encoding="utf-8",
    )
    return output_path


def timeline_rows(trades_paths: dict[str, Path]) -> list[dict[str, str]]:
    """Return stable timeline rows from split-specific trade CSV files."""
    rows: list[dict[str, str]] = []
    for split, path in sorted(trades_paths.items()):
        if not path.exists():
            continue
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                rows.append(
                    {
                        column: str(row.get(column, ""))
                        for column in TIMELINE_COLUMNS
                        if column != "split"
                    }
                    | {"split": split}
                )
    return sorted(
        rows,
        key=lambda row: (
            row.get("timestamp", ""),
            row.get("split", ""),
            row.get("market_id", ""),
        ),
    )


def render_timeline_html(
    *,
    run_id: str,
    round_id: str,
    rows: list[dict[str, str]],
) -> str:
    """Return deterministic HTML for the trade timeline artifact."""
    summary = timeline_summary(rows)
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            f'<meta name="suan-timeline-schema" content="{TIMELINE_SCHEMA_VERSION}">',
            f"<title>SuanAgent Trade Timeline - {escape(run_id)} {escape(round_id)}</title>",
            "<style>",
            timeline_css(),
            "</style>",
            "</head>",
            "<body>",
            "<main>",
            "<header>",
            "<h1>SuanAgent Trade Timeline</h1>",
            f"<p>Run <strong>{escape(run_id)}</strong> / Round <strong>{escape(round_id)}</strong></p>",
            "</header>",
            render_summary(summary),
            '<section class="panel">',
            "<h2>Trades</h2>",
            render_trade_table(rows),
            '<p class="note">Static HTML generated by deterministic local code. No external assets, scripts, or network calls.</p>',
            "</section>",
            "</main>",
            "</body>",
            "</html>",
            "",
        ]
    )


def timeline_css() -> str:
    """Return compact CSS for the static timeline page."""
    return """
:root { color-scheme: light; font-family: Arial, Helvetica, sans-serif; }
body { margin: 0; background: #f8fafc; color: #111827; }
main { max-width: 1180px; margin: 0 auto; padding: 24px; }
header { margin-bottom: 18px; }
h1 { margin: 0 0 6px; font-size: 28px; line-height: 1.2; }
h2 { margin: 0 0 12px; font-size: 18px; line-height: 1.3; }
p { margin: 0; }
.panel { background: #ffffff; border: 1px solid #d1d5db; border-radius: 8px; padding: 18px; margin: 16px 0; overflow-x: auto; }
.summary { display: grid; grid-template-columns: repeat(4, minmax(120px, 1fr)); gap: 12px; }
.tile { background: #ffffff; border: 1px solid #d1d5db; border-radius: 8px; padding: 14px; }
.tile span { display: block; color: #4b5563; font-size: 13px; margin-bottom: 6px; }
.tile strong { font-size: 20px; }
.note { color: #4b5563; font-size: 13px; margin-top: 10px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; white-space: nowrap; }
th, td { border-bottom: 1px solid #e5e7eb; padding: 7px 8px; text-align: right; }
th:first-child, td:first-child, th:nth-child(2), td:nth-child(2), th:nth-child(3), td:nth-child(3), th:last-child, td:last-child { text-align: left; }
th { color: #374151; background: #f9fafb; position: sticky; top: 0; }
tr.pnl-positive td.pnl { color: #047857; font-weight: 700; }
tr.pnl-negative td.pnl { color: #b91c1c; font-weight: 700; }
""".strip()


def timeline_summary(rows: list[dict[str, str]]) -> dict[str, Any]:
    """Return simple deterministic summary values for timeline rendering."""
    pnls = [float_or_zero(row.get("pnl", "")) for row in rows]
    slippages = [float_or_zero(row.get("slippage", "")) for row in rows]
    return {
        "trade_count": len(rows),
        "positive_trades": sum(1 for pnl in pnls if pnl > 0.0),
        "negative_trades": sum(1 for pnl in pnls if pnl < 0.0),
        "total_pnl": round(sum(pnls), 6),
        "avg_slippage": round(sum(slippages) / len(slippages), 6) if slippages else 0.0,
    }


def render_summary(summary: dict[str, Any]) -> str:
    """Return summary tiles for the trade timeline."""
    tiles = (
        ("Trade count", summary["trade_count"]),
        ("Positive", summary["positive_trades"]),
        ("Negative", summary["negative_trades"]),
        ("Total PnL", f"{summary['total_pnl']:.6f}"),
        ("Avg slippage", f"{summary['avg_slippage']:.6f}"),
    )
    return "\n".join(
        [
            '<section class="summary">',
            *[
                f'<div class="tile"><span>{escape(label)}</span><strong>{escape(value)}</strong></div>'
                for label, value in tiles
            ],
            "</section>",
        ]
    )


def render_trade_table(rows: list[dict[str, str]]) -> str:
    """Return the timeline table."""
    lines = [
        "<table>",
        "<thead>",
        "<tr>" + "".join(f"<th>{escape(column)}</th>" for column in TIMELINE_COLUMNS) + "</tr>",
        "</thead>",
        "<tbody>",
    ]
    for row in rows:
        pnl = float_or_zero(row.get("pnl", ""))
        row_class = "pnl-positive" if pnl > 0 else "pnl-negative" if pnl < 0 else "pnl-flat"
        cells = []
        for column in TIMELINE_COLUMNS:
            css_class = ' class="pnl"' if column == "pnl" else ""
            cells.append(f"<td{css_class}>{escape(row.get(column, ''))}</td>")
        lines.append(f'<tr class="{row_class}">' + "".join(cells) + "</tr>")
    lines.extend(["</tbody>", "</table>"])
    return "\n".join(lines)


def float_or_zero(value: str) -> float:
    """Return a float value or zero when parsing fails."""
    try:
        return float(value)
    except ValueError:
        return 0.0


def escape(value: object) -> str:
    """HTML-escape a value."""
    return html.escape(str(value), quote=True)
